version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
    target-branch: "dev"
    schedule:
      interval: "daily"
    reviewers:
      - "zkud"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    target-branch: "dev"
    schedule:
      interval: "daily"
    reviewers:
      - "zkud"
